name: Ultroid Workflow

on:
    push:
    workflow_dispatch:
    
env:
 GitHubName: ${{ github.event.repository.owner.login }}
 GitHubMail: ${{ github.event.repository.owner.login }}@users.noreply.github.com
 GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - uses: styfle/cancel-workflow-action@0.9.1
        name: "Cancel duplicate workflow runs"
        with:
            all_but_latest: true
            access_token: ${{ github.token }}
            
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0

      - name: PPA for Python
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
      # cache apt packages
      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: bash cmake curl ffmpeg gcc git jq make mediainfo megatools neofetch wkhtmltopdf zip software-properties-common python3.10 python3.10-dev
          version: 1.0

      - name: Clone Ultroid
        run: |
          sudo bash -c "git clone -b dev https://github.com/TeamUltroid/Ultroid.git /root/TeamUltroid || git clone -b main https://github.com/TeamUltroid/Ultroid.git /root/TeamUltroid"
      - name: Copy Python requirements
        run: |
          sudo bash -c "cp -r /root/TeamUltroid/requirements.txt ${{ github.action_path }}/requirements.txt"
          # copy optional requirements to requirements.txt
          sudo bash -c "cat /root/TeamUltroid/res*/sta*/opt*.txt >> ${{ github.action_path }}/requirements.txt"
      # cache pip packages from system site-packages
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Python requirements
        run: |
          sudo bash -c "pip install -U -r /root/TeamUltroid/requirements.txt"
          sudo bash -c "pip install -U -r /root/TeamUltroid/res*/sta*/opt*.txt"
      - name: Initialize
        continue-on-error: true
        run: |
          git config --global user.name ${GitHubName}
          git config --global user.email ${GitHubMail}
          git config --global credential.helpe  r store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
          sudo hostnamectl set-hostname errored-af
          sudo apt-get autoremove --purge
      - name: Run Ultroid
        continue-on-error: false
        run: |
          git clone ${{ secrets.CREDS }} ultroid/.env
          sudo bash action.sh
      - name: Loop workflow
        continue-on-error: false
        run: |
          git clone https://${{ secrets.GHTOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(date -u +%T%P) >> loop.txt
          git add loop.txt
          git commit -m "Workflow : Loop $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
